package view;

import entity.Reserve;
import entity.Titular;
import structures.Hash;
import structures.LDE;
import Service.*;
import DAO.*;
import javax.swing.table.DefaultTableModel;
import structures.Queue;

/**
 * Classe de entrada da interface. Ela controla a manipulação de dados do modelo
 * a fins de adequação para a view.
 * @author gabriel
 */
public class MainMenu extends javax.swing.JFrame {

    // Estruturas que armazenam as entidades
    private LDE<Titular> titulares;
    private Hash<Reserve> reservas;
    private Queue<Service> services;
    // Formulários Swing
    private TitularCadastro titCadForm;
    private ReservaCadastro resCadForm;
    private ReservaAltera resAlterForm;
    // DAOS usados no CRUD
    private TitularDAO titDAO;
    private ReserveDAO resDAO;
    // Fila usada para processar os Servicos
    private Thread serviceThread;
    // Constantes usadas na estrutura de Hash
    private final Integer ROOMS_QTTY = 20;
    private final Integer MAX_RESERVE_QTTY = 10;
    
    /**
     * Creates new form MainMenu
     */
    
    public MainMenu() {
        this.loadMock();
        this.loadServicesThread();
        initComponents();
    }
    
    private void loadMock() {
         // Inicializando dependencias titulares
        this.titulares = new LDE();
        this.titDAO = new TitularDAO(this.titulares);
        // Inicializando dependencias reservas
        this.reservas = new Hash(ROOMS_QTTY, MAX_RESERVE_QTTY);
        this.resDAO = new ReserveDAO(this.reservas);
        // Inicializando fila
        this.services = new Queue<>();
    }
    
    private void loadServicesThread() {
        this.serviceThread = new Thread(new ServiceScheduler(this.services, 1));
        this.serviceThread.start();
    }

    public void closeServicesThread() {
        this.serviceThread.stop();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        modifyReserve = new javax.swing.JButton();
        createReserve = new javax.swing.JButton();
        createTitular = new javax.swing.JButton();
        checkInButton = new javax.swing.JButton();
        checkOutButton = new javax.swing.JButton();
        nomeReserva = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        searchReserveButton = new javax.swing.JButton();
        reloadTableButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        logOut = new javax.swing.JMenuItem();
        About = new javax.swing.JMenuItem();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            this.reloadTable(),
            new String [] {
                "ID", "Quarto", "Titular", "CPF", "Dta. Inicio",
                "Hr. CheckIn", "Dta. Final", "Hr. CheckOut"
            }
        )
    );
    jScrollPane1.setViewportView(jTable1);

    modifyReserve.setText("Modificar Reserva");
    modifyReserve.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            modifyReserveActionPerformed(evt);
        }
    });

    createReserve.setText("Criar Reserva");
    createReserve.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            createReserveActionPerformed(evt);
        }
    });

    createTitular.setText("Criar Titular");
    createTitular.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            createTitularActionPerformed(evt);
        }
    });

    checkInButton.setText("Check-In");
    checkInButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            checkInButtonActionPerformed(evt);
        }
    });

    checkOutButton.setText("Check-Out");
    checkOutButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            checkOutButtonActionPerformed(evt);
        }
    });

    jLabel1.setText("Procurar reserva (quarto):");

    searchReserveButton.setText("Buscar Reserva");
    searchReserveButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            searchReserveButtonActionPerformed(evt);
        }
    });

    reloadTableButton.setText("Recarregar Tabela");
    reloadTableButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            reloadTableButtonActionPerformed(evt);
        }
    });

    jLabel2.setText("Número de quartos: " + this.ROOMS_QTTY);

    jLabel3.setText("Número MAX de reservas por quarto: " + this.MAX_RESERVE_QTTY);

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(createReserve, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(modifyReserve, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(createTitular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(checkInButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(checkOutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nomeReserva)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchReserveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(reloadTableButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(6, 6, 6)
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(nomeReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(searchReserveButton)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel3)
            .addGap(92, 92, 92)
            .addComponent(createReserve)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(createTitular)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(modifyReserve)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(checkInButton)
            .addGap(7, 7, 7)
            .addComponent(checkOutButton)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
            .addComponent(reloadTableButton)
            .addContainerGap())
    );

    jMenu1.setText("File");

    logOut.setText("Sair");
    logOut.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            logOutActionPerformed(evt);
        }
    });
    jMenu1.add(logOut);

    About.setText("Sobre");
    About.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            AboutActionPerformed(evt);
        }
    });
    jMenu1.add(About);

    jMenuBar1.add(jMenu1);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 827, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE))
            .addContainerGap())
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createReserveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createReserveActionPerformed
        this.resCadForm = new ReservaCadastro(this.titDAO, this.resDAO);
        this.resCadForm.setVisible(true);
    }//GEN-LAST:event_createReserveActionPerformed

    private void modifyReserveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyReserveActionPerformed
        Integer id, room;
        this.resAlterForm = new ReservaAltera(this.resDAO);
        id = this.getReserveId(); room = this.getReserveRoom();
        if(id != -1 && room != -1) {
            this.resAlterForm.setReserve(this.resDAO.getReserveById(id, room));
            this.resAlterForm.setVisible(true);
        }
    }//GEN-LAST:event_modifyReserveActionPerformed

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        this.closeServicesThread();
        this.dispose();
    }//GEN-LAST:event_logOutActionPerformed

    private void createTitularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createTitularActionPerformed
        this.titCadForm = new TitularCadastro(this.titDAO);
        this.titCadForm.setVisible(true);
    }//GEN-LAST:event_createTitularActionPerformed

    private boolean hasChar(String stream) {
        for (int i = 0; i < stream.length(); i++)
            if(!Character.isDigit(stream.charAt(i)))
                return true;        
        return false;
    }
    
    private void searchReserveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchReserveButtonActionPerformed
        String searchedRoom = this.nomeReserva.getText();
        if(searchedRoom.isEmpty() || this.hasChar(searchedRoom)) return;
        Object[][] data = this.reloadTable(
                new Comparable[][] {this.resDAO.getReservesByRoom(Integer.parseInt(searchedRoom))}
        );
        this.jTable1.setModel(this.getModel(data));
    }//GEN-LAST:event_searchReserveButtonActionPerformed

    private DefaultTableModel getModel(Object[][] data) {
        return new DefaultTableModel(
            data,
            new String [] {
            "ID", "Quarto", "Titular", "CPF", "Dta. Inicio",
            "Hr. CheckIn", "Dta. Final", "Hr. CheckOut"
            });
    }
    
    private void checkInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkInButtonActionPerformed
        Integer id, room;
        id = this.getReserveId(); room = this.getReserveRoom();
        if(id != -1 && room != -1)
            this.services.queue(new CheckIn(this.resDAO.getReserveById(id, room)));
    }//GEN-LAST:event_checkInButtonActionPerformed

    private void checkOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutButtonActionPerformed
        Integer id, room;
        id = this.getReserveId(); room = this.getReserveRoom();
        if(id != -1 && room != -1)
            this.services.queue(new CheckOut(this.resDAO.getReserveById(id, room)));
    }//GEN-LAST:event_checkOutButtonActionPerformed

    private void reloadTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reloadTableButtonActionPerformed
        this.jTable1.setModel(this.getModel(this.reloadTable()));
    }//GEN-LAST:event_reloadTableButtonActionPerformed

    private void AboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutActionPerformed
        Sobre panel = new Sobre();
        panel.setVisible(true);
    }//GEN-LAST:event_AboutActionPerformed

    private Integer getReserveId() {
        int index = this.jTable1.getSelectedRow();
        if(index != -1)
            return Integer.parseInt(this.jTable1.getModel().getValueAt(index, 0).toString());
        return index;
    }
    
    private Integer getReserveRoom() {
        int index = this.jTable1.getSelectedRow();
        if(index != -1)
            return Integer.parseInt(this.jTable1.getModel().getValueAt(index, 1).toString());
        return index;
    }
    
    // reload all the items
    private Object[][] reloadTable() {
        return this.reloadTable(this.resDAO.getAllReserves());
    }
    
    // reload only the given values
    private Object[][] reloadTable(Comparable[][] c) {
        String[][] temp = new String[this.reservas.getSize()][];
        int index = 0;
        for (int i = 0; i < c.length; i++) {
            for(int j = 0; j < c[i].length; j++){
                Reserve reserva = (Reserve) c[i][j];
                temp[index] = new String[] {
                        ""+reserva.getId(), ""+reserva.getRoom(), reserva.getTitular().getName(),
                        reserva.getTitular().getCPF(), reserva.getInitDate(), reserva.getCheckinHour(),
                        reserva.getEndDate(), reserva.getCheckoutHour()
                    };
                index++;
            }
        }
        return temp;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem About;
    private javax.swing.JButton checkInButton;
    private javax.swing.JButton checkOutButton;
    private javax.swing.JButton createReserve;
    private javax.swing.JButton createTitular;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenuItem logOut;
    private javax.swing.JButton modifyReserve;
    private javax.swing.JTextField nomeReserva;
    private javax.swing.JButton reloadTableButton;
    private javax.swing.JButton searchReserveButton;
    // End of variables declaration//GEN-END:variables

}
