package view;

import DAO.ReserveDAO;
import entity.Reserve;

/**
 * Alteração de reservas
 * @author ahmad   // layout
 * @author gabriel // eventos e manipulação de dados
 */

public class ReservaAltera extends javax.swing.JFrame {

    private Reserve reserve;
    private ReserveDAO resDAO;
    
    /**
     * Creates new form Reserva
     */
    public ReservaAltera(ReserveDAO resDAO) {
        this.resDAO = resDAO;
        initComponents();
    }
    
    public Reserve getReserve() {
        return reserve;
    }

    public void setReserve(Reserve reserve) {
        this.reserve = reserve;
        this.reserveIDText.setText(""+this.reserve.getId());
        this.titularCPFText.setText(this.reserve.getTitular().getCPF());
        this.roomNumberText.setText(""+this.reserve.getRoom());
        this.initDateText.setText(this.reserve.getInitDate());
        this.endDateText.setText(this.reserve.getEndDate());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        reserveIDText = new javax.swing.JTextField();
        roomNumberText = new javax.swing.JTextField();
        initDateText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        endDateText = new javax.swing.JTextField();
        changeButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        titularCPFText = new javax.swing.JTextField();

        jLabel1.setText("Número do quarto:");

        jLabel2.setText("Data entrada");

        jLabel3.setText("ID");

        reserveIDText.setEditable(false);

        jLabel4.setText("Data saída");

        changeButton.setText("Alterar");
        changeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Titular CPF");

        titularCPFText.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(changeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(45, 45, 45))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(initDateText, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(roomNumberText)
                            .addComponent(endDateText, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(reserveIDText)
                            .addComponent(titularCPFText))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(reserveIDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(titularCPFText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(roomNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(initDateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(endDateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(changeButton)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeButtonActionPerformed
        // TODO add your handling code here:
        boolean removeStatus, insertStatus;
        Reserve temp = this.reserve.clone();
        temp.setRoom(Integer.parseInt(this.roomNumberText.getText())).
            setInitDate(this.initDateText.getText()).setEndDate(this.endDateText.getText());
        removeStatus = this.resDAO.removeReserve(this.reserve);
        insertStatus = this.resDAO.insert(temp);
        this.reserve = temp;
        if(removeStatus && insertStatus)
            DialogFactory.getDialog(this, "A reserva foi alterada com sucesso.").setVisible(true);
        DialogFactory.getDialog(this, "A reserva não foi alterada.").setVisible(true);
    }//GEN-LAST:event_changeButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changeButton;
    private javax.swing.JTextField endDateText;
    private javax.swing.JTextField initDateText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField reserveIDText;
    private javax.swing.JTextField roomNumberText;
    private javax.swing.JTextField titularCPFText;
    // End of variables declaration//GEN-END:variables
}
