/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.ReserveDAO;
import DAO.TitularDAO;
import entity.Titular;
import javax.swing.JDialog;

/**
 * adastro de reservas.
 * @author ahmad   // layout
 * @author gabriel // eventos e manipulação de dados
 */

public class ReservaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form Reserva
     */
    
    private TitularDAO titDAO;
    private ReserveDAO resDAO;
    private Titular titular;
    private boolean status;
    
    public ReservaCadastro(TitularDAO titDAO, ReserveDAO resDAO) {
        this.resDAO = resDAO;
        this.titDAO = titDAO;
        this.status = false;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        roomNumberText = new javax.swing.JTextField();
        cadastroButton = new javax.swing.JButton();
        initDateText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        endDateText = new javax.swing.JTextField();
        titularCPFText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        searchTitularButton = new javax.swing.JButton();

        jLabel1.setText("Data Entrada");

        jLabel2.setText("Numero do quarto:");

        cadastroButton.setText("Cadastrar");
        cadastroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Data Saída");

        jLabel5.setText("Titular (CPF)");

        searchTitularButton.setText("?");
        searchTitularButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTitularButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(cadastroButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(endDateText)
                            .addComponent(initDateText)
                            .addComponent(roomNumberText)
                            .addComponent(titularCPFText, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchTitularButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titularCPFText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(searchTitularButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(initDateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(endDateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cadastroButton)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchTitularButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTitularButtonActionPerformed
        // TODO add your handling code here:
        this.titular = this.titDAO.getSimilarCPF(this.titularCPFText.getText());
        if(this.titular == null) {
            DialogFactory.getDialog(this, "O CPF digitado não pertence a nenhum usuário.").setVisible(true);
        } else {
            this.titularCPFText.setText(this.titular.getCPF());
            this.status = true;
            DialogFactory.getDialog(this, "Nome do usuário encontrado: " + this.titular.getName()).setVisible(true);
        }        
    }//GEN-LAST:event_searchTitularButtonActionPerformed

    private void cadastroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroButtonActionPerformed
        if(!this.status) {
            DialogFactory.getDialog(this, "É necessário vincular um usuário na reserva.").setVisible(true);
            return;
        }
        
        boolean status = this.resDAO.insert(this.resDAO.createReserve(
                Integer.parseInt(this.roomNumberText.getText())
                , this.titular, this.initDateText.getText(), this.endDateText.getText())
        );
        
        if(!status) {
            DialogFactory.getDialog(this, "O número máximo de reservas deste quarto foi atingido.").setVisible(true);
            return;
        }
        DialogFactory.getDialog(this, "Reserva Criada com sucesso").setVisible(true);
    }//GEN-LAST:event_cadastroButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastroButton;
    private javax.swing.JTextField endDateText;
    private javax.swing.JTextField initDateText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField roomNumberText;
    private javax.swing.JButton searchTitularButton;
    private javax.swing.JTextField titularCPFText;
    // End of variables declaration//GEN-END:variables
}
