var levels = [[
    {
        "l1":1,
        "l2":1,
        "rows":4,
        "columns":4,
        "none":[7,10,5,9],
        "lasers":[
            {"cell":1,"side":"n","dir":"se"}
        ],
        "targets":[
            {"cell":3,"side":"n"},
            {"cell":15,"side":"w"},
            {"cell":13,"side":"s"}
        ],
        "cells":[
            {"type":"mirror","arr":[16]},
            {"type":"glass","arr":[12]},
            {"type":"prism","arr":[15]},
            {"type":"blackhole","arr":[11]},
        ],
        "solution":[
            {"type":"mirror","arr":[12]},
            {"type":"glass","arr":[6]},
            {"type":"prism","arr":[14]},
            {"type":"blackhole","arr":[8]},
        ]
    },
    {
        "l1":1,
        "l2":2,
        "rows":3,
        "columns":4,
        "none":[3,8],
        "lasers":[
            {"cell":7,"side":"s","dir":"nw"},
            {"cell":1,"side":"n","dir":"se"}
        ],
        "targets":[
            {"cell":1,"side":"w"},
            {"cell":4,"side":"e"},
            {"cell":9,"side":"s"},
            {"cell":10,"side":"s"}
        ],
        "cells":[
            {"type":"mirror","arr":[1,9]},
            {"type":"glass","arr":[6,3]},
        ],
        "solution":[
            {"type":"mirror","arr":[5,11]},
            {"type":"glass","arr":[2,7]}
        ]
    }
]];